version: '3.4'

services:
  psp:
    container_name: psp
    networks: ['mindlogic-network']
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
     - './:/app/'
     - '/data/:/data/'
    #  - '/home/fashionteam/lcm/stylegan2-pytorch/dataset/:/dataset/'
networks: {mindlogic-network: {}}